# Generated by Django 3.1.6 on 2021-02-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=5)),
                ('discount', models.CharField(blank=True, max_length=3, null=True)),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
