# Generated by Django 3.1.6 on 2021-02-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poductdetails',
            name='category',
            field=models.CharField(blank=True, choices=[['stationery', 'Stationery'], ['vegetable', 'Vegtables/Fruits'], ['pantry', 'Pantry']], max_length=17, null=True),
        ),
    ]
