# Generated by Django 2.2.10 on 2021-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usercheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
