# Generated by Django 2.2.10 on 2021-02-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userdetail_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdetails',
            name='category',
            field=models.CharField(blank=True, choices=[['stationery', 'Stationery'], ['vegetable', 'Vegtables/Fruits'], ['pantry', 'Pantry'], ['oil', 'Oil'], ['snacks', 'Snacks']], max_length=17, null=True),
        ),
    ]
