# Generated by Django 2.2.10 on 2021-03-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210228_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdetails',
            name='category',
            field=models.CharField(blank=True, choices=[['stationery', 'Stationery'], ['vegetable', 'Vegtables/Fruits'], ['pantry', 'Pantry'], ['oil', 'Oil']], max_length=17, null=True),
        ),
    ]
