# Generated by Django 2.2.10 on 2021-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210301_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdetails',
            name='category',
            field=models.CharField(blank=True, choices=[['stationery', 'Stationery'], ['vegetable', 'Vegtables/Fruits'], ['pantry', 'Pantry'], ['personalcare', 'Personalcare'], ['cleaning', 'Cleaning'], ['beverges', 'Beverges'], ['packagedfood', 'Packagedfood'], ['cookingessential', 'Cookingessential']], max_length=17, null=True),
        ),
    ]
