# Generated by Django 2.2.10 on 2021-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210320_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='poductdetails',
            name='about',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poductdetails',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poductdetails',
            name='brandname',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poductdetails',
            name='itemweight',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poductdetails',
            name='discount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='poductdetails',
            name='price',
            field=models.CharField(max_length=6),
        ),
    ]
