# Generated by Django 2.2.10 on 2021-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210320_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdetails',
            name='category',
            field=models.CharField(blank=True, choices=[['stationery', 'Stationery'], ['vegetable', 'Vegtables/Fruits'], ['pantry', 'Pantry'], ['personalcare', 'Personalcare'], ['cleaning', 'Cleaning'], ['beverges', 'Beverges'], ['packagedfood', 'Packagedfood'], ['cookingessential', 'Cookingessential'], ['topoffer', 'Topoffer'], ['todaydeal', 'Todaydeal'], ['fruit', 'Fruit'], ['toy', 'Toy'], ['school', 'School'], ['spices', 'Spices'], ['houseware', 'houseware']], max_length=17, null=True),
        ),
    ]
