# Generated by Django 2.2.10 on 2021-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210322_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdetails',
            name='available',
            field=models.CharField(max_length=30),
        ),
    ]
